# Generated by Django 4.2.4 on 2023-08-24 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tweet_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweets',
            name='nickname',
        ),
        migrations.AddField(
            model_name='tweets',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
